FROM node:22-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

EXPOSE 4000
CMD ["node", "server.js"]

# Reset the entrypoint to default
ENTRYPOINT []

# Ensure the shell script is executable
RUN chmod +x data-update.sh